### PR TITLE
BDT models for low pT electron seeds

### PR DESCRIPTION
**Pull request by mverzett**
This PR introduce the BDT models used in the GSF Seeding in the upcoming PR for low-pT electron reconstruction. 
Two models are provided:
1. A model that is aware of the different expected pT and eta spectrum of electrons from B decays and of their different displacement.
2. A model where the background sample is reweighted to remove any discriminating power of pt and eta. Displacement is not provided.

The performance of these two models is compared to the current seeding approach (blue star) and an hypothetical seeding approach same selection as the current but with no minimal pT threshold. The triangle marker show the performance of the OR of the two trained models applying a cut that induces the same mistag rate (respectively 1, 3, and 10 times the mistag rate of the current seeding).
iterm2 sccpsn log_bdt_comparison

The performance of the same models have been tested applying a posteriori a 0.5 GeV pT cut on the track, showing the same performance in the interested phase space. It is therefore safe to apply such a cut before computing the BDT outputs to save time.
iterm2 dnihlh log_bdt_comparison

@bainbrid is also interested in following this thread.

### CODE REVIEW

**Comment by slava77** [comment]
@mverzett 
do we really need this fancy naming "improvedfullseeding_formatted" and perhaps even the date are not really functional and appear to reflect only the history of derivation.
I can imagine this way  the next version will be "evenmoreimproved"  😄

**Comment by mverzett** [comment]
Hi Slava, the name can be changed, please let me know. They reflected some studies we made with different feature sets to understand how much we could gain by adding more and more information. The date represent the internal ntuples used to run the training for internal bookkeeping.

**Comment by slava77** [comment]
I think that MC sample/campaign tag is more useful in the name than just a simple data which has a meaning only to you.

Do you expect to use both files in reco or are they integrated now "for upcoming studies", not for production?

**Comment by slava77** [comment]
@mverzett 
what is the status of the pull request for CMSSW to use these training files?

**Comment by bainbrid** [comment]
Imminent. Today or Monday ...

**Comment by slava77** [comment]
> Imminent. Today or Monday ...
> […](#)

OK, it sounds like we better wait for that to show up before merging this PR

**Comment by slava77** [comment]
@mverzett 
please let me know if you can rename the files to be a bit more functional

**Comment by mverzett** [comment]
@slava77 I just realised I made the PR from the wrong repo, I will close and re-open with the names changed

**Pull request closed without merging**
