### PR TITLE
add PHYS14 electron MVA

### PR DESCRIPTION
**Pull request by lgray**
@degano Please queue for 74X/75X/76X

@ikrav @cmkuo

### CODE REVIEW

**Comment by lgray** [comment]
Note, I have not yet deleted the files from the ongoing pull requests.
I'll do that only after coordinating with the ID conveners.

**Comment by lgray** [comment]
@slava77

**Comment by degano** [comment]
@lgray done for both here:
https://github.com/cms-sw/cmsdist/pull/1652
It will end up in tonight 76X IB, tomorrow check it out and if everythng's fine I'll backport it to 75X and 74X too.

**Comment by lgray** [comment]
Thanks @degano!

**Pull request merged**
