### PR TITLE
Updated MVA ID for low pT ele based on 94X MC

### PR DESCRIPTION
**Pull request by bainbrid**

### CODE REVIEW

**Comment by bainbrid** [comment]
This PR adds a new BDT model used in the ID module for an upcoming PR that completes the low pT electron reconstruction.

@mverzett - please can you the relevant ROC curve demonstrating the models performance, and perhaps some further detail?

The model is identical to the one used by EGamma "MVA ID" but has been retrained using B->K(*)ee MC samples generated with 9_4_X.

This model, along with the two BDT models included as part of [this](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/10) closed PR and used by the Seeding module, will be updated in due course with trainings based on 10_2_X MC samples. 

@slava77 @perrotta

**Comment by bainbrid** [comment]
The [cms-sw#25696](https://github.com/cms-sw/cmssw/pull/25696) PR relies on the model in this PR.

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by perrotta** [comment]
+1
(Could a cmsdist PR be made out of this, so that tests for #25696 can be run?)

**Comment by mrodozov** [comment]
+externals
for bookkeeping

**Comment by bainbrid** [comment]
hi - has this PR integrated into the master IBs? I don't see the new file e.g. here: 
```/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_5_X_2019-02-04-1100/external/slc6_amd64_gcc700/data/RecoEgamma/ElectronIdentification/data/LowPtElectrons/RunII_Fall17_LowPtElectrons_mva_id.xml.gz```

**Comment by smuzaffar** [comment]
@bainbrid , this is not yet merged in cmssw.  Both CMSSW pr and cmsdist PR are still open. Once the following two PR are merged then this new files will be avialable.
https://github.com/cms-sw/cmsdist/pull/4650
https://github.com/cms-sw/cmssw/pull/25753

**Pull request merged**
