### PR TITLE
Add weights for HZZ ID

### PR DESCRIPTION
**Pull request by apetkovi1**
This PR is to add weights for Run3 HZZ electron ID

### CODE REVIEW

**Comment by smuzaffar** [comment]
only new data files, should be tested and merged along with https://github.com/cms-sw/cmssw/pull/43430

**Comment by a-kapoor** [comment]
> only new data files, should be tested and merged along with [cms-sw/cmssw#43430](https://github.com/cms-sw/cmssw/pull/43430)

sorry @smuzaffar I am unable to understand this comment. This PR only contains new files.

**Comment by smuzaffar** [comment]
@a-kapoor , comment was to remind myself to not start the tests here :-)  Testing data PRs with only new files makes no sense as tests are always going to pass.

**Comment by a-kapoor** [comment]
> @a-kapoor , comment was to remind myself to not start the tests here :-) Testing data PRs with only new files makes no sense as tests are always going to pass.

Perfect! Thanks. :-)

**Comment by mmusich** [comment]
Looks like https://github.com/cms-sw/cmssw/pull/43430 was merged without this, which (as usual) is causing massive IB failures.

**Comment by a-kapoor** [comment]
> Looks like [cms-sw/cmssw#43430](https://github.com/cms-sw/cmssw/pull/43430) was merged without this, which (as usual) is causing massive IB failures.

Oops! I believe the way out here is to backport the cmsdist PR after merging this one? Do we need to make the PR? @smuzaffar would you please to help us with how to proceed? Sorry we didn't realize this was still not merged.

**Comment by smuzaffar** [comment]
+externals

@rappoccio, @antoniovilela this should have been merged along with https://github.com/cms-sw/cmssw/pull/43430 . I am force merging it to get it in 11h IB

**Pull request merged**
