### PR TITLE
Final BDT models based on 10.2 MC samples 

### PR DESCRIPTION
**Pull request by bainbrid**
@Slava77 @perrotta

These BDT models are used by the ```LowPtGsfElectronSeedProducer``` and ```LowPtGsfElectronIDProducer``` modules in the low pT electron reconstruction.

They are to be used in conjunction with by this PR: #25936.

They are intended for the 10_2_X release cycle only. (We will release update models for the 10_5_X release cycles and later.)

The performance of the two Seed models is shown below and compared to the default EGamma seeding approach (blue circle). 
 
image

### CODE REVIEW

**Comment by bainbrid** [comment]
@mverzett is interested to follow this thread.

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by mrodozov** [comment]
@slava77 ping

**Comment by slava77** [comment]
> @slava77 ping

@perrotta will probably have a final say on this.

@bainbrid 
I'm curious if all 9 new files (about 200MB) are really going to be used in production jobs.
In particular, I only see the 3 xml.gz files used in cms-sw/cmssw#25936.
Please clarify on the pkl files.

**Comment by bainbrid** [comment]
@slava77 

Only the three *Autumn18* files will be used. 

The .xml files define the models used as defined by the library used to generate them (scikit-learn),  before their conversion to be compliant with TMVA. They are intended to be kept for reproducibility in the future. 

Do you prefer we remove all unnecessary files from the PR?

**Comment by slava77** [comment]
On 2/19/19 12:04 PM, bainbrid wrote:
> Do you prefer we remove all unnecessary files from the PR?
> 

yes, please.
Preferably, please rewrite the commits so that the pkl files do not show
up in the git history at all.

**Comment by bainbrid** [comment]
@slava77 
Removed obsolete files and squashed the commit involving the pkl files.

**Comment by perrotta** [comment]
@mrodozov @smuzaffar : could you please prepare two cmsdata pull requests out of this one, one for 10_5_X and one for 10_6_X?

Thank you!

**Comment by bainbrid** [comment]
The 10_5_X release is using a different training currently, and the files are named differently.  

Doing as you suggested would require configuration changes. I would hold off on this for now, so we can discuss further, perhaps in tomorrow's meeting? 

rob

**Comment by mrodozov** [comment]
So 10_2 only it is for now if I got that right ?

**Comment by perrotta** [comment]
Apparently yes. Thank you!

Mircho Rodozov <notifications@github.com> ha scritto:

**Comment by bainbrid** [comment]
@mrodozov @smuzaffar

After discussing internally, and in the RECO meeting on Friday, we think it would be a good idea to propagate these models to master. 

Please could you please prepare a new cmsdata pull request out of this one, to be used in master. Ideally, we’d back port to 10_5_X as well, if everyone agrees? 

I will need to create a new corresponding PR for cms-sw to update the configs to point to the new models (which have different names) and set the appropriate working points. I’ll do this later this evening.

**Comment by perrotta** [comment]
@mrodozov @smuzaffar could you please prepare the corresponding of #4724 for the master, so that the tests for #26012 can get started?
Thank you!

**Comment by smuzaffar** [comment]
@gudrutis , can you please take care of this? Just update the cmsdist/data/cmsswdata.txt with newer version

**Comment by gudrutis** [comment]
I updated RecoEgamma-ElectronIdentification to V01-01-03 on master and started the tests on #26012 .

**Pull request merged**
