### PR TITLE
Backport of #18: HtoZZ UL training xml files

### PR DESCRIPTION
**Pull request by jainshilpi**
This PR is the backport of #18  and adds the xml file for UL HtoZZ ID for 3 years. Relevant PR for putting in cfgs to use this is done here: #33620

### CODE REVIEW

**Comment by perrotta** [comment]
please test with #33620

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmssw/pull/33620

**Comment by perrotta** [comment]
+1
- Tests with this data external have been just successfully completed in the sibling PR #33620
- These are all new files, with no modification of the existing ones, and will therefore not modify current workflows in 10_6
- Once this one is merged, also PR #33620 will be signed by reco

**Comment by perrotta** [comment]
The error in the (FastSIm) addOn looks unrelated to me...

**Comment by mrodozov** [comment]
if it's from the IB probably it isn't

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#33620

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
