### PR TITLE
HtoZZ UL training

### PR DESCRIPTION
**Pull request by jainshilpi**
This PR adds the xml file for UL HtoZZ ID for 3 years. Relevant PR for putting in cfgs to use this will be done today.

### CODE REVIEW

**Comment by perrotta** [comment]
+reconstruction
- To be used by #33517, for UL analyses, and possible future nanoAOD productions
- Only additional IDs will be merged, with no effect on the existing ones: no changes expected for current standard workflows
- #33517 will be signed once this cms-data PR will be available in a IB

**Comment by jainshilpi** [comment]
I will create a back-port in 106X of this one by today. thanks

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
these are all new files and can be merged and included in CMSSW before cmssw changes

**Comment by smuzaffar** [comment]
cms-sw/cmsdist#6870 is merged and these changes will in in today's 23h00 IB

**Comment by perrotta** [comment]
@smuzaffar do you have any suggestion for @jainshilpi about how to backport this to 10_6_X?
Should she backport this cms-data PR, or is it enough to bacport the tag, as you did for the master withhttps://github.com/cms-sw/cmsdist/pull/6870?

**Comment by jainshilpi** [comment]
Just to mention that I tried creating this branch: https://github.com/cms-egamma/RecoEgamma-ElectronIdentification/tree/HtoZZID_106X
which doesn't need any CMSSW version. If I try to do PR in master, then I can just see my commits. However, if I try to do PR in 106X, I can see commits from low pT electrons.

**Comment by smuzaffar** [comment]
@jainshilpi , please open a PR for https://github.com/cms-data/RecoEgamma-ElectronIdentification/tree/CMSSW_10_6_X branch.

**Comment by smuzaffar** [comment]
`CMSSW_10_6_X` branch is based on the tag `V01-01-04` used in 10.6.X IBs

**Pull request merged**
