### PR TITLE
Add triggering mva weights for spring15 Triggering MVA ID

### PR DESCRIPTION
**Pull request by lgray**
@degano These will be needed for an upcoming pull request, please queue for 76X/75X/74X. Thanks!

@ikrav

### CODE REVIEW

**Comment by lgray** [comment]
@degano Would be nice to get this in for the 1100am IB, if possible.

**Comment by lgray** [comment]
@degano Thanks!

**Comment by degano** [comment]
@lgray For 76X the PR has been merged here: https://github.com/cms-sw/cmsdist/pull/1888.
The 7[5-4]X PRs are ready as well, please let me know once you're satisfied with 76X so I can merge those as well.

**Comment by lgray** [comment]
@degano Sure, it'll be much today before I can confirm anything in 76X. Will let you know.

**Comment by lgray** [comment]
@degano everything is fine in 76X. Please push this to 75X and 74X as well. Thanks!

**Comment by degano** [comment]
@lgray Done, cheers.

**Pull request merged**
