### PR TITLE
LowPtElectrons: latest BDT model for ID (ROOT file format)

### PR DESCRIPTION
**Pull request by bainbrid**
**This PR concerns changes to the BDT model used for the identification of LowPtElectrons.**

**This PR is required by: cms-sw/cmssw#31220**

 ---

_File: LowPtElectrons/LowPtElectrons_ID_2020Sept15.root_
- This PR contains the BDT model described by a GBRForest object stored within a ROOT file.
- The file name in question is `LowPtElectrons/LowPtElectrons_ID_2020Sept15.root`.
- The new model is a "placeholder" that will be replaced in due course, based on a final retraining is performed with new MC samples.
- For the record, the relevant model hyperparameters are depth15 and trees=1000.
- The model expects regressed energy inputs (but this has a negligible impact on model performance).

_File: LowPtElectrons/RunII_Autumn18_LowPtElectrons_mva_id.xml.gz_
- The original `LowPtElectrons/RunII_Autumn18_LowPtElectrons_mva_id.xml.gz` has also been updated.
- The original version is broken and of no use. 
- The updated version in this PR is not used by default, but it is a viable model (tag 2019Aug07).
- We ask to add it to this PR "for the record" and as a baseline for future checks/studies. 

Validation has been performed with both "placeholder" models and their performances are consistent with our expectations.

### CODE REVIEW

**Comment by bainbrid** [comment]
@crovelli @cavalari

**Comment by bainbrid** [comment]
@guitargeek

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#31220

**Comment by slava77** [comment]
> I found compilation error when building:

this looks related to more recent updates in the externals (apparently a test with cms-data leads to picking up of the latest externals).
The tests will be restarted when the next IB shows up

**Comment by mrodozov** [comment]
I'm seeing similar error in ppc IB let me rerun it and see if it persists

**Comment by slava77** [comment]
it looks like a rebase to squash intermediate commits is in order here, so that only the new file shows up in the history.

While testing locally I noticed that .git is 458 MB (after checking out this PR topic branch CMSBParking:from-CMSSW_10_2_15_2020Sept15), compared to 134MB without this PR (after checking out of the master of the cms-data/RecoEgamma-ElectronIdentification repo).

@mrodozov @smuzaffar do we have some size limitations of data repositories? is there some history cleanup in place for cms-data repositories that may explain the difference (above) between 458 MB and 134 MB, or will this PR really increase the pack size by so much?

**Comment by smuzaffar** [comment]
@slava77 , github repository size limitations are in [a]. Changing binary files between different commits is not a good idea as every comits just adds a new file. We normally do not run any cleanup but in this case cleanup is also not going to help as the changed files are part of commit history. 

@bainbrid can you please force push just a single commit with updates files?

[a]  https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/what-is-my-disk-quota
We recommend repositories remain small, ideally less than 1 GB, and less than 5 GB is strongly recommended. Smaller repositories are faster to clone and easier to work with and maintain. Individual files in a repository are strictly limited to a 100 MB maximum size limit.

**Comment by bainbrid** [comment]
Hi @slava77 @smuzaffar I've just taken a look myself at this repo. I've just forced pushed to the `CMSBParking:from-CMSSW_10_2_15_2020Sept15` branch, which should improve things. Here are some comments.

**Bottom line: the repo is now 172MB in size.**

---

1) Note that this model is still the placeholder. Perhaps I can play the same trick when we have the final training. Please advise.

2) I checked cms-data/RecoEgamma-ElectronIdentification:master 

```
git clone --single-branch --branch master git@github.com:cms-data/RecoEgamma-ElectronIdentification.git $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data

cd $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/
du -sh .git/
134M .git/

ll LowPtElectrons/
total 42795
-rw-r--r--. 1 bainbrid zh 15691522 Nov 25 10:58 RunII_Autumn18_LowPtElectrons_displaced_pt_eta_biased.xml.gz
-rw-r--r--. 1 bainbrid Hz  8519842 Nov 25 10:58 RunII_Autumn18_LowPtElectrons_mva_id.xml.gz
-rw-r--r--. 1 bainbrid zh 19609111 Nov 25 10:58 RunII_Autumn18_LowPtElectrons_unbiased.xml.gz

4379aec (HEAD -> master, tag: V01-02-00, origin/master, origin/HEAD) Merge pull request #14 from CMSBParking/updateLowPtId
2aa9f04 Extra variables for LowPtElectrons Id added. Depth10, no regression
f747396 (tag: V01-01-03) Merge pull request #13 from CMSBParking/master
c79bcd5 added Autumn18 trainings
19f4edf (tag: V01-01-02) Merge pull request #12 from bainbrid/master
7dd2159 Updated MVA ID for low pT ele based on 94X MC
295f1da (tag: V01-01-01) Merge pull request #11 from CMSBParking/master
28e964b renamed files
570c025 BDT models for low pT electron seeds
fe2b5b5 (tag: V01-01-00) Merge pull request #9 from guitargeek/Ele_MVA_V2
```

The low-pT developments are introduced after `V01-01-00` and we are currently at `V01-02-00` (==`master`). The repo size is 134MB. 

3) Before the low-pT developments we were at `V01-01-00`:

```
git clone --single-branch --branch V01-01-00 git@github.com:cms-data/RecoEgamma-ElectronIdentification.git $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data

cd $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/
du -sh .git/
62M .git/

ll LowPtElectrons/
"No such file or directory"
```

So far, we have increased from 62MB to 134MB.

4) The `CMSBParking:from-CMSSW_10_2_15_2020Sept15` branch for this PR (before the force push) gave us:

```
git clone --single-branch --branch from-CMSSW_10_2_15_2020Sept15 git@github.com:CMSBParking/RecoEgamma-ElectronIdentification.git $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data

cd $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/
du -sh .git/
261M	.git/

ll LowPtElectrons/
total 92099
-rw-r--r--. 1 bainbrid zh 40066383 Nov 25 11:03 LowPtElectrons_ID_2020Sept15.root
-rw-r--r--. 1 bainbrid zh 15691522 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_displaced_pt_eta_biased.xml.gz
-rw-r--r--. 1 bainbrid zh 18939927 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_mva_id.xml.gz
-rw-r--r--. 1 bainbrid zh 19609111 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_unbiased.xml.gz

git log --oneline
f23b440 (HEAD -> from-CMSSW_10_2_15_2020Sept15, origin/from-CMSSW_10_2_15_2020Sept15) Merge branch 'master' of github.com:cms-data/RecoEgamma-ElectronIdentification into from-CMSSW_10_2_15_2020Sept15
f8e8547 switch from depth13 to depth15
120515a depth=13, ntrees=1000, uses regressed energy
4379aec Merge pull request #14 from CMSBParking/updateLowPtId
```

So an anticipated increase from 134MB to 261MB.

5) And after the force push we have:

```
git clone --single-branch --branch from-CMSSW_10_2_15_2020Sept15 git@github.com:CMSBParking/RecoEgamma-ElectronIdentification.git $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data

cd $CMSSW_BASE/external/$SCRAM_ARCH/data/RecoEgamma/ElectronIdentification/data/
du -sh .git/
172M	.git/

ll LowPtElectrons/
total 92099
-rw-r--r--. 1 bainbrid zh 40066383 Nov 25 11:03 LowPtElectrons_ID_2020Sept15.root
-rw-r--r--. 1 bainbrid zh 15691522 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_displaced_pt_eta_biased.xml.gz
-rw-r--r--. 1 bainbrid zh 18939927 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_mva_id.xml.gz
-rw-r--r--. 1 bainbrid zh 19609111 Nov 25 11:03 RunII_Autumn18_LowPtElectrons_unbiased.xml.gz

git log --oneline
e6d9191 (HEAD -> from-CMSSW_10_2_15_2020Sept15) depth=15, ntrees=1000, uses regressed energy
4379aec (tag: V01-02-00, origin/master, origin/HEAD, master) Merge pull request #14 from CMSBParking/updateLowPtId
```

which removes the 120515a commit and reduces the anticipated increase from 134MB->261MB to 134MB->172MB. 

I hope this is acceptable!

**Comment by slava77** [comment]
> which removes the [120515a](https://github.com/cms-data/RecoEgamma-ElectronIdentification/commit/120515a3f7502398ed33f02cfe0984d9540c4442) commit and reduces the anticipated increase from 134MB->261MB to 134MB->172MB.
> 
> I hope this is acceptable!

Nice.
Thank you for the update and the investigation.

**Comment by slava77** [comment]
+1

based on the review here and the results observed in cms-sw/cmssw#31220 (e.g. in https://github.com/cms-sw/cmssw/pull/31220#issuecomment-734053697 and the follow up comments)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
