### PR TITLE
Added Run3 electron MVA ID weight files from EGM POG

### PR DESCRIPTION
**Pull request by Prasant1993**
**PR Description:**
From EGM POG
Electron MVA IDs have been optimized for Run3.
The .root version of weight files have been added.

### CODE REVIEW

**Comment by a-kapoor** [comment]
@cms-sw/reconstruction-l2 @cms-sw/orp-l2 Hi, can we get a go-ahead for this? This is needed for e/gamma IDs in 12_6.
Thanks.

**Comment by mandrenguyen** [comment]
+1

**Comment by a-kapoor** [comment]
@perrotta Just need your approval. :-)

**Comment by rappoccio** [comment]
+1

**Comment by makortel** [comment]
Many runTheMatrix workflows are failing in CMSSW_13_0_X_2022-12-08-2300 because #40230 was merged but this one wasn't. I suppose the bot didn't merge the PR yet because of  the `externals-l2` signature is still missing (@smuzaffar @iarspider @aandvalenzuela).

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
I have merged this ( and cmsdist PR to update it in cmssw) now and restated an IB

**Comment by rappoccio** [comment]
Thanks @smuzaffar ! Sorry, I should have pinged you yesterday to preempt the IB failures.

**Comment by smuzaffar** [comment]
@rappoccio , no we do not need 12.6.X branch here. We just need to backport the cmsdist PR https://github.com/cms-sw/cmsdist/pull/8222 for 12.6.X. I will open it and merge it for next 12.6.X

**Pull request merged**
