### PR TITLE
Convert xml.gz files to .root files

### PR DESCRIPTION
**Pull request by swagata87**
This is an attempt to address this issue: https://github.com/cms-sw/cmssw/issues/37867

Used `convertXMLToGBRForestROOT` command to convert Electorn's MVA IDs' xml.gz files to .root files.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/38339

**Comment by perrotta** [comment]
+1
- It replaces xml.gz files with root files, as requested by #38339

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
merge

**Pull request merged**
