### PR TITLE
LowPtElectrons: convert Seed BDTs from XML to ROOT file format

### PR DESCRIPTION
**Pull request by bainbrid**
This PR converts the formats (from XML to ROOT) of two files containing the weights of two BDT models used by the low pT electron seeding step in the reconstruction chain. 

The effect is to reduce the file size by a factor two for both files, and to reduce the memory consumption and CPU time when parsing the weights files. 

This was done in response to the issues raised here: https://github.com/cms-sw/cmssw/issues/34707

A similar change was made previously, but on the weights file for the BDT model used by the low pT electron ID module (as opposed to the seeding step, as above), which solved the issues raised here: https://github.com/cms-sw/cmssw/issues/28780

### CODE REVIEW

**Comment by bainbrid** [comment]
This PR is used by https://github.com/cms-sw/cmssw/pull/34908

**Comment by slava77** [comment]
+reconstruction

for cmsdist this should be merged together with cms-sw/cmssw#34908

**Comment by perrotta** [comment]
- This has to be merged together with #34908: @smuzaffar (just to learn how to deal with it in the future) how do we manage to synchronize the merging of the PR in cms-data and in cmssw? I think I should wait for a "+1" from externals, once tests finish: then we'll merge the two PRs at the same time, so that they end up in the same IB?
- By the way, this cms-data PR was already succesfully tested together with #34908, while now it reports about an error from a addOn test: let see what is it...

**Comment by smuzaffar** [comment]
+externals
@perrotta , once cms-data external PR is ready (means already successfully tested directly via cms-data PR or indirectly via cmssw PR) then we merge it and bot automatically tags the cms-data changes and creates a cmsdist PR.  If you want then you can restart a fresh test to test cmsdist cmssw PRs otheriwse normally it is ok to just merge the cmsdist and cmssw PRs.

Because of `+reco` comment bot started the test here and as it was ran without cmssw PR that is why there are failures. I would suggest to ignore these errors and goahead with the merge. Testing it via cmssw was good enough.

**Comment by perrotta** [comment]
+1
- To go together with #34908

**Comment by perrotta** [comment]
merge

**Comment by bainbrid** [comment]
Is this https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/22#issuecomment-902014413 something I need to worry about? Presumably so? 

Why is it only showing up now?

**Comment by mrodozov** [comment]
because the test has been started, and when the pr is merged the test isn't stopped. and also because it ran without the corresponding cmssw PR

**Pull request merged**
