### PR TITLE
LowPtElectrons: 2021May17 model for 12_0_X

### PR DESCRIPTION
**Pull request by bainbrid**
This PR adds the following weights file, on the master branch for the 12_0_X release cycle:
- `LowPtElectrons_ID_2021May17.root`

The 2021May17 file is enabled by the bParking modifier, to used during the UL RE-RECO of the BParking data set, as required by the PR cms-sw/cmssw#33725

The model performances can be found in [this](https://indico.cern.ch/event/1034467/contributions/4344267/attachments/2248230/3813485/LowPtElectrons_PPDMay21.pdf) presentation.

### CODE REVIEW

**Comment by slava77** [comment]
+1

based on tests in cms-sw/cmssw#33725

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
please check this, in case it's still possible to have this merged for 2300, or at least for 1100.
Thank you.

The PR only adds a new file.

**Comment by smuzaffar** [comment]
+externals
only adds new file, so safe to integrate it for next IB

**Comment by smuzaffar** [comment]
@slava77 , this should be available in 23h00 IB

**Comment by slava77** [comment]
> @slava77 , this should be available in 23h00 IB

Thank you.

**Pull request merged**
