### PR TITLE
add electron EAs for PHYS14

### PR DESCRIPTION
**Pull request by lgray**
New electron effective areas for PHYS14 cut based IDs.

### CODE REVIEW

**Comment by lgray** [comment]
@degano needed for https://github.com/cms-sw/cmssw/pull/9002 and https://github.com/cms-sw/cmssw/pull/9003

**Comment by davidlange6** [comment]
Hi @degano , @lgray  - sorry I have missed any discussion of this - are we expecting this file to grow greatly in size? Its a headache to have to change an external for 10 lines of text.

**Comment by lgray** [comment]
@davidlange6 No, but I was asked by @slava77 to move all things in data/ areas to cms-dist.

**Comment by slava77** [comment]
I've asked for a separate data external driven by 
RecoEgamma/PhotonIdentification/data/PHYS14/photon_general_MVA_phys14_pu20bx25_EB_V1.weights.xml
(18 K lines).

Also, as I understand electron IDs based on MVA are coming and will sit in this directory.

**Comment by lgray** [comment]
Yes, exactly.

(Sent from my Nexus 6)

**Comment by davidlange6** [comment]
are we then missing a piece of this pull request? at the moment we have one new file of a few lines?

**Comment by lgray** [comment]
I think that is for cmsdist. Alessandro?

**Comment by degano** [comment]
@lgray I think that @davidlange6 is referring to this PR which only contains a single files containing 5 non-commented lines.
In the PR I prepared for cmsdist both this update and the new repository for PhotonIdentification are togheter targetted to 75X.

**Comment by lgray** [comment]
Hi Alessandro,

This also needs to target the next 74X.

-L

On Mon, May 11, 2015 at 1:53 PM, Alessandro Degano <notifications@github.com

**Comment by slava77** [comment]
To respond to this https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/1#issuecomment-100807698 with more arguments: it's not very practical and is also confusing to have some (smaller) files in the source tree in cms-sw/cmssw repo and some (larger) files in the same logical directory in cms-data/package repository

**Comment by degano** [comment]
@slava77 @lgray I merged the PR for the 74X branch as well here: https://github.com/cms-sw/cmsdist/pull/1561.

**Pull request merged**
